name: Continuous Integration

on:
  pull_request:
    branches:
      - main
jobs:
  automation-test-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: |
          npm run ci:test
          npx wait-on http://localhost:5173